[project]
name = "mcp-client-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.50.0",
    "bs4>=0.0.2",
    "fastapi>=0.115.12",
    "mcp>=1.7.1",
    "python-dotenv>=1.1.0",
]
